package com.javalab.movieapp;

public class Constants {
    public static final Integer USER_ROLE_ID = 1;
    public static final String ADMIN_ROLE_ID = "2";
    public static final Long DEFAULT_LANGUAGE_ID = 2L;
    public static final String LOGIN_PARAM = "login";
    public static final String MOVIEAPP_SERVLET_MAPPING = "/movieapp";
    public static final String PASSWORD_PARAM = "pass";
    public static final String BIRTHDATE_PARAM = "birthD";
    public static final String IMAGE_PARAM = "image";
    public static final String RATE_PARAM = "rate";
    public static final String LOCATION_PARAM = "location";
    public static final String DURATION_PARAM = "duration";
    public static final String BUDGET_PARAM = "budget";
    public static final String RELEASE_DATE_PARAM = "releaseDate";
    public static final String EMAIL_PARAM = "email";
    public static final String ROLE_ID_PARAM = "roleId";
    public static final String USER_ID_PARAM = "userId";
    public static final String PERSON_ID_PARAM = "personId";
    public static final String ORIGINAL_NAME_PARAM = "oName";
    public static final String ORIGINAL_SURNAME_PARAM = "oSurname";
    public static final String ORIGINAL_TITLE_PARAM = "oTitle";
    public static final String TRANSLATED_TITLE_PARAM = "tTitle";
    public static final String DESCRIPTION_PARAM = "description";
    public static final String TRANSLATED_NAME_PARAM = "tName";
    public static final String TRANSLATED_SURNAME_PARAM = "tSurname";
    public static final String USER_ATTRIB = "user";
    public static final String ERROR_ATTRIB = "error";
    public static final String MOVIE_ATTRIB = "movie";
    public static final String MOVIE_LIST_ATTRIB = "movies";
    public static final String PERSON_LIST_ATTRIB = "people";
    public static final String GENRE_LIST_ATTRIB = "genres";
    public static final String LANGUAGE_LIST_ATTRIB = "languages";
    public static final String USER_LIST_ATTRIB = "users";
    public static final String LANGUAGE_ID_ATTRIB = "languageId";
    public static final String LANGUAGE_ID_PARAM = "languageId";
    public static final String MOVIE_ID_PARAM = "movieId";
    public static final String GENRE_ID_PARAM = "genreId";
    public static final String NEW_PASSWORD_PARAM = "newPass";
    public static final String CONFIRM_PASSWORD_PARAM = "confirmPass";
    public static final String NAME_PARAM = "name";
    public static final String SEARCH_PARAM = "search";
    public static final String LOCALE_ATTRIB = "locale";
    public static final String ORIGIN_PARAM = "origin";
    public static final String ADD_GENRE_ACTION = "/addGenre";
    public static final String UPDATE_GENRE_ACTION = "/updateGenre";
    public static final String UPDATE_USER_ACTION = "/updateUser";
    public static final String ADD_USER_ACTION = "/addUser";
    public static final String ADD_MOVIE_ACTION = "/addMovie";
    public static final String UPDATE_MOVIE_ACTION = "/updateMovie";
    public static final String UPDATE_LANGUAGE_ACTION = "/updateLanguage";
    public static final String ADD_LANGUAGE_ACTION = "/addLanguage";
    public static final String ADD_PERSON_ACTION = "/addPerson";
    public static final String UPDATE_PERSON_ACTION = "/updatePerson";
    public static final String CREATE_MOVIE_LOCAL_INFO_ACTION = "/addMovieLocal";
    public static final String UPDATE_MOVIE_LOCAL_INFO_ACTION = "/updateMovieLocal";
    public static final String CREATE_PERSON_LOCAL_INFO_ACTION = "/addPersonLocal";
    public static final String UPDATE_PERSON_LOCAL_INFO_ACTION = "/updatePersonLocal";
    public static final String MOVIE_LIST_PAGE = "WEB-INF/jsp/movieList.jsp";
    public static final String USER_LIST_PAGE = "WEB-INF/jsp/userList.jsp";
    public static final String GENRE_LIST_PAGE = "WEB-INF/jsp/genreList.jsp";
    public static final String PERSON_LIST_PAGE = "WEB-INF/jsp/personList.jsp";
    public static final String LANGUAGE_LIST_PAGE = "WEB-INF/jsp/languageList.jsp";
    public static final String AUTHORIZATION_PAGE = "WEB-INF/jsp/authorization.jsp";
    public static final String MOVIE_PAGE = "WEB-INF/jsp/movie.jsp";
    public static final String HOME_PAGE = "/homePage.jsp";
    public static final String PERSON_ROLE_ACTOR = "1";
    public static final String PERSON_ROLE_DIRECTOR = "2";
    public static final String PERSON_ROLE_WRITER = "3";
    public static final String LIST_LANGUAGE_ACTION = "listLanguage";
    public static final String LIST_GENRE_ACTION = "listGenre";
    public static final String LIST_USER_ACTION = "listUser";
    public static final String LIST_MOVIE_ACTION = "listMovie";
    public static final String LIST_PERSON_ACTION = "listPerson";
    public static final String MOVIE_INFO_ACTION = "movieInfo?movieId=";
    public static final String MOVIE_CREW_INFO_ACTION = "movieCrewInfo?movieId=";
    public static final Integer STRING_MAX_LENGTH = 50;
    public static final Integer TITLE_MAX_LENGTH = 255;
    public static final Integer LONG_MAX_LENGTH = 20;
    public static final Integer INT_MAX_LENGTH = 11;
    public static final Integer MOVIE_RATE_MAX_LENGTH = 2;
    public static final String NUMBER_REGEX = "\\d+";
    public static final String EMAIL_REGEX = "([.[^@\\s]]+)@([.[^@\\s]]+)\\.([a-z]+)";
    public static final String WRONG_PASS_OR_EMAIL_ERROR = "wrongPassOrEmail";
    public static final String INCORRECT_INPUT_ERROR = "incorrectInput";
    public static final String DATABASE_ERROR = "databaseError";
    public static final String ACTION_NOT_FOUND_ERROR = "actionNotFound";
    public static final String INCORRECT_CRUCIAL_URL_PARAM_ERROR = "incorrectCrucialUrlParam";
    public static final String EMAIL_IS_ALREADY_TAKEN_ERROR = "emailIsTaken";
    public static final String LOCALE_DATA_EXISTS_ERROR = "localeDataExists";





}
